### ISSUE TITLE
I found a small problem 

### ISSUE THREAD

**Issue by zzuruichao** [jiacheng-ye/DocL-NER#1]
You say "We use standard CoNLL format with each character and its label split by a whitespace in a line. The "BMES" tag scheme is prefered. Make sure to use -DOCSTART- to indicate the begining of a document."  But I found CoNLL tag scheme is "BIES"

**Comment by jiacheng-ye** [comment]
I'm sorry to make you misunderstand. Actually, the two schemes are equivalent (i.e., `M` for `Middle`, `I` for `In`).
